REM - ADMIN
c:\programdata\chocolatey\bin\psexec \\ADMHP -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\ADMHV -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\ADMEV -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\ADMHS -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\ADMES -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - IT and PROD
c:\programdata\chocolatey\bin\psexec \\GYMMED -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\SMSHTV -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\SMSITA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\SMSITC -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - ELEM Staff
c:\programdata\chocolatey\bin\psexec \\E1AT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E2AT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E2BT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E3AT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E3BT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E4AT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E4BT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E5AT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E5BT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E6AT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E6BT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E7AT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E7BT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E8AT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E8BT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\ESTAFF -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\SHOPRF -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\SHOPRD -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - ELEM Student
c:\programdata\chocolatey\bin\psexec \\E1AA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E1BA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E1BB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E1BC -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E1BD -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E4AA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E4AB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E4BA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E4BB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E5AA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E5AB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E5BA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E5BB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E6AA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E6AB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E6BA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E6BB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E7AA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E7AB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E7BA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E8AA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E8AB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E8BA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\E8BB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - ELEM LIB
c:\programdata\chocolatey\bin\psexec \\LIBT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\LIBA -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\LIBB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\LIBC -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - RESOURCE
c:\programdata\chocolatey\bin\psexec \\RES-MP -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\RES-CD -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\RES-GR -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\RES-SM -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\RES-G -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\RES-LL -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - Lower Level
c:\programdata\chocolatey\bin\psexec \\REST -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FRENCH -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\CAFE -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\MUSLJ -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\MUSB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - Before After
c:\programdata\chocolatey\bin\psexec \\BA1 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BA2 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BA3 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BA4 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BA5 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - Highschool Staff
c:\programdata\chocolatey\bin\psexec \\BLT -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BLSB -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H102T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H103T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H104T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H105T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H201T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H202T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H203T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H204T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H205T -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H200A -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H200B -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\GYMLL -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\GYMJL -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - Highschool Student
c:\programdata\chocolatey\bin\psexec \\H105A -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H105B -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H105C -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H105D -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H203A -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H203B -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H203C -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H203D -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H203E -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H203F -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H204A -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H204B -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H204C -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\H204D -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - LABS - FFS
c:\programdata\chocolatey\bin\psexec \\FFS01 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS02 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS03 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS04 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS05 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS06 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS07 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS08 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS09 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS10 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS11 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS12 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS13 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS14 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS15 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS16 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS17 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS18 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS19 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS20 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS21 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS22 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS23 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS24 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS25 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS26 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS27 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS28 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS29 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\FFS30 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM - LABS - Science
c:\programdata\chocolatey\bin\psexec \\BL01 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL02 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL03 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL04 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL05 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL06 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL07 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL08 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL09 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL10 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL11 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL12 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL13 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL14 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL15 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL16 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL17 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL18 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL19 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL20 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL21 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL22 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL23 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL24 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL25 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL26 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL27 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL28 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL29 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL30 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
REM Business Lab
c:\programdata\chocolatey\bin\psexec \\BL01 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL02 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL03 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL04 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL05 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL06 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL07 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL08 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL09 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL10 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL11 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL12 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL13 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL14 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL15 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL16 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL17 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL18 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL19 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL20 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL21 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL22 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL23 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL24 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL25 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL26 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL27 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL28 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL29 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y
c:\programdata\chocolatey\bin\psexec \\BL30 -d c:\programdata\chocolatey\bin\cup.exe chocolatey -y